### ISSUE TITLE
Add `undefined` local var.

### ISSUE THREAD

**Issue by jdalton** [substack/insert-module-globals#53]
Webpack adds `undefined` as a local undefined var in the bundles IIFE but I noticed browserify did not. Would you all be open to that?

**Comment by jdalton** [comment]
Ping @zertosh.

**Comment by zertosh** [comment]
Hey @jdalton, sorry I missed this.

To add something to the actual bundle factory, it'd have to be done in [browser-pack](https://github.com/substack/browser-pack). However, the factory call already has [more arguments](https://github.com/substack/browser-pack/blob/aadeabea66feac48193d27d233daf1c85209357e/prelude.js#L36) than are [actually defined](https://github.com/substack/browser-pack/blob/aadeabea66feac48193d27d233daf1c85209357e/index.js#L73). Some of those extra arguments are used for [module deduping](https://github.com/substack/node-browserify/blob/f7e626ca75bd925a584f9b0fe8ff9d4b8e90f188/index.js#L655-L658) and [more](https://github.com/zertosh/bpack-debug/blob/6ff6ba9a7f705d0660d6ac3b964e578ae9337594/bpack-debug.js#L7-L8). So that really complicates things there.

To add it in another IIFE only when it's actually used (like with `__filename` or `process`), then insert-module-globals is the thing to do it. Though I'm not so sure about adding it as default. It would certainly bloat modules and significantly increase build times. If a user really wants to guarantee  the value of `undefined`, they can add it themselves with:

```js
var b = browserify({
  entries: 'index.js'
  insertGlobalVars: {
    undefined: function () {
        return 'void 0';
    }
  }
});
```

Or, if they want something that actually replaces `undefined` with `void 0`, then they can use babel's [`undefined-to-void` transform](http://babeljs.io/docs/advanced/transformers/spec/undefined-to-void/).

Am I missing something though?

PS: I love your awesome work on lodash!

**Comment by jdalton** [comment]
Cool! Thanks! I think `insertGlobalVars` will do nicely.

**Comment by jdalton** [comment]
Hey @zertosh. OT – could you look at [this PR](https://github.com/rackt/redux/pull/611/files#diff-d9d75cc1dda9c5e912390983ac6b263aR20). Is there a way to do something similar to `webpack.NormalModuleReplacementPlugin` in Browserify. I'm curious so I can document the options available to devs.

**Comment by zertosh** [comment]
@jdalton I believe that [pathmodify](https://www.npmjs.com/package/pathmodify) is comparable

**Comment by jdalton** [comment]
Thanks Andres! \cc @phated
